### ISSUE TITLE
--all flag does not give all output comparisons if using pre-built pca data during evaluation

### ISSUE THREAD

**Issue by sjneph** [JustinChu/ntsm#6]
assuming $fs is an array of file results from running ntsmCount:

// --all gives all pairwise comparisons as expected
ntsmEval --all -t 16 $fs > summary.tsv 

// --all only gives pairwise comparisons that are determined to be from the same sample
//   centered=data/human_sites_center.txt and
//   mtx=data/human_sites_rotationMat.tsv
ntsmEval --all -t 16 -n $centered -p $mtx $fs > summary.tsv

**Comment by JustinChu** [comment]
Using PCA projection will compare samples that seem similar in PCA space, so `-a` may output samples that are not related or the same sample.

If I'm interpreting your question correctly this is related to https://github.com/JustinChu/ntsm/issues/5

Let me know if that helps or need more clarification on how `-a` works with the PCA heuristic.

*Edit. I edited the readme slightly to include this information.

**Comment by sjneph** [comment]
Okay, #5 helped my understanding.  I'll close out this issue, thanks.
