### ISSUE TITLE
ntsmSiteGen question

### ISSUE THREAD

**Issue by VonPoo** [JustinChu/ntsm#9]
Hi Justin,

I hope this message finds you well.

2 days ago, I installed version 1.1.0 of your software, and the installation completed successfully. However, when I attempted to run the following command:

```bash
ntsmSiteGen generate-sites name=prefix ref=reference.fa vcf=snps.vcf
```
I received the error message:

```bash
ntsmSiteGen: command not found
```
I noticed that you made some recent changes to the README.md document a few minutes ago. Could these changes be related to the issue I'm experiencing, or is it possibly due to another problem?

Your software has already shown tremendous advantages in previous issues, and I am very enthusiastic about promoting the final stable version once this issue is resolved.

Thank you very much for your time and assistance.

Best regards,
VonPoo

**Comment by JustinChu** [comment]
Hi, I was making some changes for a conda release.  Thanks for letting me know. I've released 1.2.0 as well for that purpose but I'll be sure to include it in the install prefix when using the `make install` command in another release and will let you know when I'm finished.

For now, it should work if you run it directly from the source as that program is not a binary that needs to be compiled but a makefile-based pipeline.

**Comment by VonPoo** [comment]
Hi Justin,

Thank you very much for your prompt response and for releasing version 1.2.0.

I got that the `ntsmSiteGen` command can be run directly from the source using the makefile-based pipeline for now. I will proceed with testing it using this method.

I look forward to the release of the final stable version and wish you all the best with its completion.

Best regards,
VonPoo

**Comment by JustinChu** [comment]
the current version 1.2.1 should now install the scripts to your path.

**Comment by VonPoo** [comment]
Exciting news! I’m currently testing version 1.1.0. Thank you very much for your valuable feedback and prompt responses.
